version: '3'

networks:
  backend_network: # Réseau privé API <-> DB (inaccessible de lexterieur)
    internal: true
  frontend_network: # Réseau public Frontend <-> API
    driver: bridge

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: librarydb
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 5s
  api:
    build: ./node-api
    expose:
      - "3000"
#    ports:
#        - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_network
      - frontend_network
  frontent:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - frontend_network

volumes:
  db_data:
